allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  bufferutil: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
  utf-8-validate: true
  workerd: true

